import { Specialist, Appointment, Patient } from "../../models";
import { createTestSpecialist, createTestPatient } from "./helpers";
import { sequelize } from "../../utils/connectToDb";

beforeAll(async () => {
  await Specialist.drop({
    cascade: true,
  });

  await Patient.drop({
    cascade: true,
  });

  await Appointment.drop({
    cascade: true,
  });

  await sequelize.sync();
});

test("complete patient instance is returned with autogenerated primary key", async () => {
  const specialist = await createTestSpecialist();
  const patient = await createTestPatient(specialist.specialistId);

  expect(
    "patientId" in patient &&
      "name" in patient &&
      "email" in patient &&
      "phone" in patient &&
      "dateOfBirth" in patient &&
      "gender" in patient &&
      "address" in patient &&
      "specialistId" in patient
  );
  expect(patient.patientId).toEqual(1);
  expect(patient.specialistId).toEqual(1);
});

//

afterAll(async () => {
  await sequelize.close();
});
