import Specialist from "../../models/specialist";
import { Appointment, Patient } from "../../models";
import { sequelize } from "../../utils/connectToDb";

beforeAll(async () => {
  await Specialist.drop({
    cascade: true,
  });

  await Patient.drop({
    cascade: true,
  });

  await Appointment.drop({
    cascade: true,
  });

  await sequelize.sync();
});

test("specialist is returned with autogenerated primary key", async () => {
  const specialist = await Specialist.create({
    name: "test specialist",
    speciality: "testing",
  });

  expect("specialistid" in specialist && "name" in specialist && "speciality" in specialist);
  expect(specialist.specialistId).toEqual(1);
  await sequelize.close();
});

afterAll(async () => {
  await sequelize.close();
});
