/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { sequelize } from "../../utils/connectToDb";
import { User } from "../../models";
import { User as UserType } from "../../types";
import { dropUserTable } from "../helpers/models";

beforeEach(async () => await dropUserTable());

test("complete user instance is returned with autogenerated primary key", async () => {
  const user = await User.create({
    name: "test user",
    username: "testuser",
    password: "secret",
  });

  expectUser(user);
});

const expectUser = (user: UserType) => {
  expect(user).toMatchObject<UserType>({
    id: expect.any(Number),
    name: expect.any(String),
    username: expect.any(String),
    password: expect.any(String),
  });
};

afterAll(async () => await sequelize.close());
